#!/usr/bin/env python3
"""Import state.json / awb_registry.json / threads.json into Postgres.

Emits SQL on stdout; apply with psql. Idempotent - every statement is an upsert
or a guarded insert, so re-running changes nothing.

  python3 migrate.py --dry  | psql ...     # rolls back, prints what would land
  python3 migrate.py        | psql ...     # commits

Deliberate gaps, so nothing is invented:
  - emails_sent.from_addr / to_addrs / body_* are NULL for imported mail. The
    JSON never stored them. MAIL_TO from .env is NOT backfilled as a guess.
  - email_replies rows carry message_id only; the bodies are long gone. They
    exist so the idempotency key is populated and an already-processed reply is
    never commented a second time.
  - processed{} records no reply attribution, so its history rows are attached
    to the thread's first reply and labelled in matched_via.
"""
import json
import sys
from pathlib import Path

D = Path("/home/ubuntu/scripts/utkarsh/Automation-Bluedart-Customer-Success")
DRY = "--dry" in sys.argv


def q(v):
    """SQL literal. None -> NULL."""
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


out = []
w = out.append

w("-- Generated by migrate.py. Do not edit.")
w("BEGIN;")
w("")

# ------------------------------------------------------------------ state.json
state = json.loads((D / "state.json").read_text())
wm = state.get("last_ticket_number")

w("-- ============ runs (from state.json) ============")
w(f"""INSERT INTO runs (started_at, finished_at, status, stage_reached, attempts,
                  watermark_ticket, watermark_utc, modified_utc, export_file,
                  rows_count, mailer_sent)
SELECT {q(state.get('last_run_ist'))}, {q(state.get('last_run_ist'))}, 'committed', 'mailed', 1,
       {q(wm)}, {q(state.get('last_created_utc'))}, {q(state.get('last_modified_utc'))},
       {q(state.get('last_file'))}, {state.get('rows') or 0},
       {'true' if state.get('last_mail_sent_ist') else 'false'}
WHERE NOT EXISTS (
    SELECT 1 FROM runs WHERE status='committed' AND watermark_ticket={q(wm)});""")
w("")

RUN = f"(SELECT id FROM runs WHERE status='committed' AND watermark_ticket={q(wm)} ORDER BY id LIMIT 1)"

# ------------------------------------------------------------------ tickets
registry = json.loads((D / "awb_registry.json").read_text()).get("awbs", {})
threads = json.loads((D / "threads.json").read_text()).get("threads", [])

# ticket_number -> {ticket_id, awb, created_utc}
tk = {}
for awb, v in registry.items():
    num = str(v.get("ticketNumber") or "").strip()
    if not num:
        continue
    tk.setdefault(num, {})
    tk[num]["ticket_id"] = v.get("ticketId") or tk[num].get("ticket_id")
    tk[num]["awb"] = awb
    tk[num]["created_utc"] = v.get("created_utc")
for t in threads:
    for num, v in (t.get("tickets") or {}).items():
        num = str(num).strip()
        tk.setdefault(num, {})
        tk[num].setdefault("ticket_id", v.get("ticketId"))
        tk[num].setdefault("awb", v.get("awb"))
        tk[num].setdefault("created_utc", None)

w(f"-- ============ tickets ({len(tk)} stubs) ============")
w("-- Ticket rows were never persisted, so most columns are NULL. ticket_id is")
w("-- the field that matters: it is what the Desk comment API needs.")
for num, v in sorted(tk.items()):
    w(f"""INSERT INTO tickets (ticket_number, ticket_id, awb, created_utc, first_run_id)
VALUES ({q(num)}, {q(v.get('ticket_id'))}, {q(v.get('awb'))}, {q(v.get('created_utc'))}, NULL)
ON CONFLICT (ticket_number) DO UPDATE SET
    ticket_id   = COALESCE(EXCLUDED.ticket_id,   tickets.ticket_id),
    awb         = COALESCE(EXCLUDED.awb,         tickets.awb),
    created_utc = COALESCE(EXCLUDED.created_utc, tickets.created_utc),
    last_seen_at = now();""")
w("")

# ------------------------------------------------------------------ awb_registry
w(f"-- ============ awb_registry ({len(registry)} rows) ============")
for awb, v in sorted(registry.items()):
    num = str(v.get("ticketNumber") or "").strip()
    if not num:
        continue
    w(f"""INSERT INTO awb_registry (awb, ticket_number, created_utc)
VALUES ({q(awb)}, {q(num)}, {q(v.get('created_utc'))})
ON CONFLICT (awb) DO NOTHING;""")
w("")

# ------------------------------------------------------------------ emails_sent
STATUS_MAP = {"awaiting_reply": "awaiting_reply", "completed": "completed"}
w(f"-- ============ emails_sent ({len(threads)} threads) ============")
for t in threads:
    mid = t["message_id"]
    tickets = t.get("tickets") or {}
    processed = t.get("processed") or {}
    status = STATUS_MAP.get(t.get("status"), "awaiting_reply")
    # A thread with some but not all tickets answered is partially_answered.
    if status != "completed" and processed:
        status = "partially_answered"
    # Only the 26-Aug thread matches the run in state.json (sent_ist agrees to
    # the millisecond). The 25-Aug thread predates it, so its run is unknown.
    run = RUN if t.get("sent_ist", "")[:19] == (state.get("last_run_ist") or "")[:19] else "NULL"
    w(f"""INSERT INTO emails_sent (message_id, run_id, kind, subject, sent_at, status,
                         ticket_count, followup_sent_at, followup_suppressed,
                         followup_suppressed_reason, completed_at)
VALUES ({q(mid)}, {run}, 'escalation', {q(t.get('subject'))}, {q(t.get('sent_ist'))},
        {q(status)}, {len(tickets)}, {q(t.get('followup_sent_ist'))},
        {'true' if t.get('followup_suppressed') else 'false'},
        {q(t.get('followup_suppressed_reason'))}, {q(t.get('completed_ist'))})
ON CONFLICT (message_id) DO NOTHING;""")
w("")

# ------------------------------------------------------------------ email_replies
nrep = sum(len(t.get("seen_replies") or []) for t in threads)
w(f"-- ============ email_replies ({nrep} rows) ============")
w("-- message_id only. Present so an already-read reply is never reprocessed.")
for t in threads:
    email = f"(SELECT id FROM emails_sent WHERE message_id={q(t['message_id'])})"
    for rmid in (t.get("seen_replies") or []):
        w(f"""INSERT INTO email_replies (email_id, message_id, received_at, fetched_at, status_rows_found)
VALUES ({email}, {q(rmid)}, NULL, now(), 0)
ON CONFLICT (message_id) DO NOTHING;""")
w("")

# ------------------------------------------------------------------ email_tickets
nlines = sum(len(t.get("tickets") or {}) for t in threads)
w(f"-- ============ email_tickets ({nlines} line items) ============")
for t in threads:
    email = f"(SELECT id FROM emails_sent WHERE message_id={q(t['message_id'])})"
    seen = t.get("seen_replies") or []
    first_reply = (f"(SELECT id FROM email_replies WHERE message_id={q(seen[0])})"
                   if seen else "NULL")
    processed = t.get("processed") or {}
    for num, v in (t.get("tickets") or {}).items():
        p = processed.get(str(num))
        if p:
            w(f"""INSERT INTO email_tickets (email_id, ticket_number, awb, line_status,
                           latest_status_text, latest_reply_id, answered_at, desk_posted_at)
VALUES ({email}, {q(num)}, {q(v.get('awb'))}, 'answered',
        {q(p.get('status'))}, {first_reply}, {q(p.get('commented_ist'))}, {q(p.get('commented_ist'))})
ON CONFLICT (email_id, ticket_number) DO NOTHING;""")
        else:
            w(f"""INSERT INTO email_tickets (email_id, ticket_number, awb, line_status)
VALUES ({email}, {q(num)}, {q(v.get('awb'))}, 'awaiting_reply')
ON CONFLICT (email_id, ticket_number) DO NOTHING;""")
w("")

# ------------------------------------------------------------------ reply_ticket_statuses
nproc = sum(len(t.get("processed") or {}) for t in threads)
w(f"-- ============ reply_ticket_statuses ({nproc} history rows) ============")
w("-- processed{} records no reply attribution, so these attach to the thread's")
w("-- first reply and say so in matched_via. Nothing here is presented as exact.")
for t in threads:
    seen = t.get("seen_replies") or []
    if not seen:
        continue
    reply = f"(SELECT id FROM email_replies WHERE message_id={q(seen[0])})"
    for num, p in (t.get("processed") or {}).items():
        via = (p.get("via") or "") + " (legacy import; exact reply attribution unavailable)"
        w(f"""INSERT INTO reply_ticket_statuses (reply_id, ticket_number, awb, status_text,
                                  matched_via, desk_posted_at, created_at)
VALUES ({reply}, {q(num)}, {q(p.get('awb'))}, {q(p.get('status'))},
        {q(via.strip())}, {q(p.get('commented_ist'))}, {q(p.get('commented_ist'))})
ON CONFLICT (reply_id, ticket_number) DO NOTHING;""")
w("")

# ------------------------------------------------------------------ reconciliation
w("-- ============ reconciliation ============")
w(f"""\\echo ''
\\echo 'source JSON  ->  runs 1 | tickets {len(tk)} | awb_registry {len(registry)} | emails_sent {len(threads)} | email_replies {nrep} | email_tickets {nlines} | reply_ticket_statuses {nproc}'
\\echo ''""")
w("""SELECT 'runs' AS table_name, count(*) FROM runs
UNION ALL SELECT 'tickets', count(*) FROM tickets
UNION ALL SELECT 'awb_registry', count(*) FROM awb_registry
UNION ALL SELECT 'emails_sent', count(*) FROM emails_sent
UNION ALL SELECT 'email_replies', count(*) FROM email_replies
UNION ALL SELECT 'email_tickets', count(*) FROM email_tickets
UNION ALL SELECT 'reply_ticket_statuses', count(*) FROM reply_ticket_statuses
ORDER BY 1;""")
w("")
w("""\\echo '-- outstanding work the pipeline must still chase:'
SELECT e.subject, e.status, count(*) FILTER (WHERE t.line_status='awaiting_reply') AS unanswered
FROM emails_sent e JOIN email_tickets t ON t.email_id = e.id
GROUP BY e.id, e.subject, e.status ORDER BY e.subject;""")
w("")
w("ROLLBACK;" if DRY else "COMMIT;")

sys.stdout.write("\n".join(out) + "\n")
